# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/suhai/Desktop/3-ugersHardware/hdmi-out/hdmi-out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_timer_0_0/hdmi_out_axi_timer_0_0.xci
# IP: The module: 'hdmi_out_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/suhai/Desktop/3-ugersHardware/hdmi-out/hdmi-out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_timer_0_0/hdmi_out_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/suhai/Desktop/3-ugersHardware/hdmi-out/hdmi-out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_timer_0_0/hdmi_out_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/suhai/Desktop/3-ugersHardware/hdmi-out/hdmi-out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_timer_0_0/hdmi_out_axi_timer_0_0.xci
# IP: The module: 'hdmi_out_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/suhai/Desktop/3-ugersHardware/hdmi-out/hdmi-out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_timer_0_0/hdmi_out_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/suhai/Desktop/3-ugersHardware/hdmi-out/hdmi-out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_timer_0_0/hdmi_out_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_out_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
